version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - "uxio0"
      - "moisses89"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - "uxio0"
      - "moisses89"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - "uxio0"
      - "moisses89"
